apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImEzVmhibWQ1ZFdGdU1UazVNVG9oVVVGYVFIZHplRE5sWkdNPSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  name: kyhub
  namespace: microcraft
type: kubernetes.io/dockerconfigjson