apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: microcraft
data:
  # Startup mode, "api" starts the API server.
  MODE: api
  # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
  LOG_LEVEL: INFO
  # enable DEBUG mode to output more logs
  # DEBUG : true
  # A secret key that is used for securely signing the session cookie and encrypting sensitive information on the database. You can generate a strong key using `openssl rand -base64 42`.
  SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
  # The base URL of console application web frontend, refers to the Console base URL of WEB service if console domain is
  # different from api or web app domain.
  # example: http://cloud.dify.ai
  CONSOLE_WEB_URL: ""
  # Password for admin user initialization.
  # If left unset, admin user will not be prompted for a password when creating the initial admin account.
  INIT_PASSWORD: ""
  # The base URL of console application api server, refers to the Console base URL of WEB service if console domain is
  # different from api or web app domain.
  # example: http://cloud.dify.ai
  CONSOLE_API_URL: ""
  # The URL prefix for Service API endpoints, refers to the base URL of the current API service if api domain is
  # different from console domain.
  # example: http://api.dify.ai
  SERVICE_API_URL: ""
  # The URL prefix for Web APP frontend, refers to the Web App base URL of WEB service if web app domain is different from
  # console or api domain.
  # example: http://udify.app
  APP_WEB_URL: ""
  # File preview or download Url prefix.
  # used to display File preview or download Url to the front-end or as Multi-model inputs;
  # Url is signed and has expiration time.
  FILES_URL: ""
  # File Access Time specifies a time interval in seconds for the file to be accessed.
  # The default value is 300 seconds.
  FILES_ACCESS_TIMEOUT: "300"
  # When enabled, migrations will be executed prior to application startup and the application will start after the migrations have completed.
  MIGRATION_ENABLED: "true"
  # The configurations of postgres database connection.
  # It is consistent with the configuration in the "db" service below.
  DB_USERNAME: postgres
  DB_PASSWORD: "WbrTpN3g7q"
  DB_HOST: postgres-headless-svc.microcraft.svc.cluster.local
  # DB_HOST: "10.96.0.10"
  DB_PORT: "5432"
  DB_DATABASE: postgres
  # The configurations of redis connection.
  # It is consistent with the configuration in the "redis" service below.
  REDIS_HOST: redis.microcraft.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""
  REDIS_USE_SSL: "false"
  # use redis db 0 for redis cache
  REDIS_DB: "0"
  # The configurations of celery broker.
  # Use redis as the broker, and redis db 1 for celery broker.
  CELERY_BROKER_URL: redis://redis:6379/1
  # Specifies the allowed origins for cross-origin requests to the Web API, e.g. https://dify.app or * for all origins.
  WEB_API_CORS_ALLOW_ORIGINS: "*"
  # Specifies the allowed origins for cross-origin requests to the console API, e.g. https://cloud.dify.ai or * for all origins.
  CONSOLE_CORS_ALLOW_ORIGINS: "*"
  # CSRF Cookie settings
  # Controls whether a cookie is sent with cross-site requests,
  # providing some protection against cross-site request forgery attacks
  #
  # Default: `SameSite=Lax, Secure=false, HttpOnly=true`
  # This default configuration supports same-origin requests using either HTTP or HTTPS,
  # but does not support cross-origin requests. It is suitable for local debugging purposes.
  #
  # If you want to enable cross-origin support,
  # you must use the HTTPS protocol and set the configuration to `SameSite=None, Secure=true, HttpOnly=true`.
  #
  # The type of storage to use for storing user files. Supported values are `local` and `s3` and `azure-blob` and `google-storage`, Default: `local`
  STORAGE_TYPE: local
  # The path to the local storage directory, the directory relative the root path of API service codes or absolute path. Default: `storage` or `/home/john/storage`.
  # only available when STORAGE_TYPE is `local`.
  STORAGE_LOCAL_PATH: storage
  # The S3 storage configurations, only available when STORAGE_TYPE is `s3`.
  S3_ENDPOINT: "https://xxx.r2.cloudflarestorage.com"
  S3_BUCKET_NAME: "difyai"
  S3_ACCESS_KEY: "ak-difyai"
  S3_SECRET_KEY: "sk-difyai"
  S3_REGION: "us-east-1"
  # The Azure Blob storage configurations, only available when STORAGE_TYPE is `azure-blob`.
  AZURE_BLOB_ACCOUNT_NAME: "difyai"
  AZURE_BLOB_ACCOUNT_KEY: "difyai"
  AZURE_BLOB_CONTAINER_NAME: "difyai-container"
  AZURE_BLOB_ACCOUNT_URL: "https://<your_account_name>.blob.core.windows.net"
  # The Google storage configurations, only available when STORAGE_TYPE is `google-storage`.
  GOOGLE_STORAGE_BUCKET_NAME: "yout-bucket-name"
  # if you want to use Application Default Credentials, you can leave GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64 empty.
  GOOGLE_STORAGE_SERVICE_ACCOUNT_JSON_BASE64: "your-google-service-account-json-base64-string"
  # The type of vector store to use. Supported values are `weaviate`, `qdrant`, `milvus`, `relyt`.
  VECTOR_STORE: weaviate
  # The Weaviate endpoint URL. Only available when VECTOR_STORE is `weaviate`.
  WEAVIATE_ENDPOINT: http://weaviate.microcraft.svc.cluster.local:8080
  # The Weaviate API key.
  WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
  # The Qdrant endpoint URL. Only available when VECTOR_STORE is `qdrant`.
  QDRANT_URL: http://qdrant:6333
  # The Qdrant API key.
  # -----------
  QDRANT_API_KEY: difyai123456
  # The Qdrant client timeout setting.
  QDRANT_CLIENT_TIMEOUT: "20"
  # The Qdrant client enable gRPC mode.
  QDRANT_GRPC_ENABLED: "false"
  # The Qdrant server gRPC mode PORT.
  QDRANT_GRPC_PORT: "6334"
  # Milvus configuration Only available when VECTOR_STORE is `milvus`.
  # The milvus host.
  MILVUS_HOST: 127.0.0.1
  # The milvus host.
  MILVUS_PORT: "19530"
  # The milvus username.
  MILVUS_USER: root
  # The milvus password.
  MILVUS_PASSWORD: Milvus
  # The milvus tls switch.
  MILVUS_SECURE: "false"
  # relyt configurations
  RELYT_HOST: db
  RELYT_PORT: "5432"
  RELYT_USER: postgres
  RELYT_PASSWORD: difyai123456
  RELYT_DATABASE: postgres
  # pgvector configurations
  PGVECTOR_HOST: pgvector
  PGVECTOR_PORT: "5432"
  PGVECTOR_USER: postgres
  PGVECTOR_PASSWORD: WbrTpN3g7q
  PGVECTOR_DATABASE: dify
  # Mail configuration, support: resend, smtp
  MAIL_TYPE: ""
  # default send from email address, if not specified
  MAIL_DEFAULT_SEND_FROM: "YOUR EMAIL FROM (eg: no-reply <no-reply@dify.ai>)"
  SMTP_SERVER: ""
  SMTP_PORT: "587"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_USE_TLS: "true"
  # the api-key for resend (https://resend.com)
  RESEND_API_KEY: ""
  RESEND_API_URL: https://api.resend.com
  # The DSN for Sentry error reporting. If not set, Sentry error reporting will be disabled.
  SENTRY_DSN: ""
  # The sample rate for Sentry events. Default: `1.0`
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  # The sample rate for Sentry profiles. Default: `1.0`
  SENTRY_PROFILES_SAMPLE_RATE: "1.0"
  # Notion import configuration, support public and internal
  NOTION_INTEGRATION_TYPE: public
  NOTION_CLIENT_SECRET: you-client-secret
  NOTION_CLIENT_ID: you-client-id
  NOTION_INTERNAL_SECRET: you-internal-secret
  # The sandbox service endpoint.
  CODE_EXECUTION_ENDPOINT: "http://sandbox:8194"
  CODE_EXECUTION_API_KEY: dify-sandbox
  CODE_MAX_NUMBER: "9223372036854775807"
  CODE_MIN_NUMBER: "-9223372036854775808"
  CODE_MAX_STRING_LENGTH: "80000"
  TEMPLATE_TRANSFORM_MAX_LENGTH: "80000"
  CODE_MAX_STRING_ARRAY_LENGTH: "30"
  CODE_MAX_OBJECT_ARRAY_LENGTH: "30"
  CODE_MAX_NUMBER_ARRAY_LENGTH: "1000"
  # SSRF Proxy server
  SSRF_PROXY_HTTP_URL: "http://ssrf_proxy:3128"
  SSRF_PROXY_HTTPS_URL: "http://ssrf_proxy:3128"
  # Indexing configuration
  INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: "1000"