apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microcraft-api
  name: microcraft-api
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: microcraft-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microcraft-api
    spec:
      containers:
      - image: kuangyuan1991/microcraft_api:1.0.0
        imagePullPolicy: IfNotPresent
        name: microcraft-api-j7gp6
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
        - configMapRef:
            name: api-config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: kyhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
