"""add file uuid to UploadFile

Revision ID: 1c920fb64ea3
Revises: 35ea58e0e9f0
Create Date: 2024-05-27 09:00:10.819078

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c920fb64ea3'
down_revision = '35ea58e0e9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_uuid', models.StringUUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.drop_column('file_uuid')

    # ### end Alembic commands ###
