"""add account_id in apps

Revision ID: 35ea58e0e9f0
Revises: 47cc7df8c4f3
Create Date: 2024-05-17 10:07:02.866008

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ea58e0e9f0'
down_revision = '47cc7df8c4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_account_id', models.StringUUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('creator_account_id')

    # ### end Alembic commands ###
