apiVersion: v1
kind: Service
metadata: 
  name: microcraft-api-service
  labels:
    app: microcraft-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5001
    protocol: TCP
  selector:
    app: microcraft-api
